<?php

namespace ContainerODFGSaj;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_OFpVnn4Service extends App_KernelTestDebugContainer
{
    /**
     * Gets the private '.service_locator.oFpVnn4' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.oFpVnn4'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'loyaltyCard' => ['privates', '.errored..service_locator.oFpVnn4.App\\Entity\\LoyaltyCard', NULL, 'Cannot autowire service ".service_locator.oFpVnn4": it needs an instance of "App\\Entity\\LoyaltyCard" but this type has been excluded in "config/services.yaml".'],
        ], [
            'loyaltyCard' => 'App\\Entity\\LoyaltyCard',
        ]);
    }
}
