<?php

namespace ContainerODFGSaj;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getLoyaltyCardService extends App_KernelTestDebugContainer
{
    /**
     * Gets the private '.errored..service_locator.DxJ_gkE.App\Entity\LoyaltyCard' shared service.
     *
     * @return \App\Entity\LoyaltyCard
     */
    public static function do($container, $lazyLoad = true)
    {
        throw new RuntimeException('Cannot autowire service ".service_locator.DxJ_gkE": it needs an instance of "App\\Entity\\LoyaltyCard" but this type has been excluded in "config/services.yaml".');
    }
}
