<?php

namespace ContainerWaivRzI;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_PQaCGoqService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.PQaCGoq' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.PQaCGoq'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'product' => ['privates', '.errored..service_locator.PQaCGoq.App\\Entity\\Products', NULL, 'Cannot autowire service ".service_locator.PQaCGoq": it needs an instance of "App\\Entity\\Products" but this type has been excluded in "config/services.yaml".'],
            'productsRepository' => ['privates', 'App\\Repository\\ProductsRepository', 'getProductsRepositoryService', true],
        ], [
            'product' => 'App\\Entity\\Products',
            'productsRepository' => 'App\\Repository\\ProductsRepository',
        ]);
    }
}
