<?php

namespace ContainerHMsUfVo;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_M2Z5CajService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.m2Z5Caj' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.m2Z5Caj'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'coupon' => ['privates', '.errored..service_locator.m2Z5Caj.App\\Entity\\Coupon', NULL, 'Cannot autowire service ".service_locator.m2Z5Caj": it needs an instance of "App\\Entity\\Coupon" but this type has been excluded in "config/services.yaml".'],
        ], [
            'coupon' => 'App\\Entity\\Coupon',
        ]);
    }
}
