<?php

namespace Proxies\__CG__\App\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class LoyaltyCard extends \App\Entity\LoyaltyCard implements \Doctrine\ORM\Proxy\InternalProxy
{
    use \Symfony\Component\VarExporter\LazyGhostTrait {
        initializeLazyObject as __load;
        setLazyObjectAsInitialized as public __setInitialized;
        isLazyObjectInitialized as private;
        createLazyGhost as private;
        resetLazyObject as private;
    }

    private const LAZY_OBJECT_PROPERTY_SCOPES = [
        "\0".parent::class."\0".'card_number' => [parent::class, 'card_number', null],
        "\0".parent::class."\0".'card_type' => [parent::class, 'card_type', null],
        "\0".parent::class."\0".'coupons' => [parent::class, 'coupons', null],
        "\0".parent::class."\0".'id' => [parent::class, 'id', null],
        "\0".parent::class."\0".'iduser' => [parent::class, 'iduser', null],
        "\0".parent::class."\0".'personalized_offer' => [parent::class, 'personalized_offer', null],
        "\0".parent::class."\0".'points' => [parent::class, 'points', null],
        'card_number' => [parent::class, 'card_number', null],
        'card_type' => [parent::class, 'card_type', null],
        'coupons' => [parent::class, 'coupons', null],
        'id' => [parent::class, 'id', null],
        'iduser' => [parent::class, 'iduser', null],
        'personalized_offer' => [parent::class, 'personalized_offer', null],
        'points' => [parent::class, 'points', null],
    ];

    public function __isInitialized(): bool
    {
        return isset($this->lazyObjectState) && $this->isLazyObjectInitialized();
    }

    public function __serialize(): array
    {
        $properties = (array) $this;
        unset($properties["\0" . self::class . "\0lazyObjectState"]);

        return $properties;
    }
}
