<?php

namespace Proxies\__CG__\App\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class User extends \App\Entity\User implements \Doctrine\ORM\Proxy\InternalProxy
{
    use \Symfony\Component\VarExporter\LazyGhostTrait {
        initializeLazyObject as __load;
        setLazyObjectAsInitialized as public __setInitialized;
        isLazyObjectInitialized as private;
        createLazyGhost as private;
        resetLazyObject as private;
    }

    private const LAZY_OBJECT_PROPERTY_SCOPES = [
        "\0".parent::class."\0".'adresse' => [parent::class, 'adresse', null],
        "\0".parent::class."\0".'civilite' => [parent::class, 'civilite', null],
        "\0".parent::class."\0".'contacts' => [parent::class, 'contacts', null],
        "\0".parent::class."\0".'date_create' => [parent::class, 'date_create', null],
        "\0".parent::class."\0".'deletedAt' => [parent::class, 'deletedAt', null],
        "\0".parent::class."\0".'email' => [parent::class, 'email', null],
        "\0".parent::class."\0".'expiredAt' => [parent::class, 'expiredAt', null],
        "\0".parent::class."\0".'id' => [parent::class, 'id', null],
        "\0".parent::class."\0".'idloyaltycard' => [parent::class, 'idloyaltycard', null],
        "\0".parent::class."\0".'idpanier' => [parent::class, 'idpanier', null],
        "\0".parent::class."\0".'name' => [parent::class, 'name', null],
        "\0".parent::class."\0".'paniers' => [parent::class, 'paniers', null],
        "\0".parent::class."\0".'password' => [parent::class, 'password', null],
        "\0".parent::class."\0".'roles' => [parent::class, 'roles', null],
        'adresse' => [parent::class, 'adresse', null],
        'civilite' => [parent::class, 'civilite', null],
        'contacts' => [parent::class, 'contacts', null],
        'date_create' => [parent::class, 'date_create', null],
        'deletedAt' => [parent::class, 'deletedAt', null],
        'email' => [parent::class, 'email', null],
        'expiredAt' => [parent::class, 'expiredAt', null],
        'id' => [parent::class, 'id', null],
        'idloyaltycard' => [parent::class, 'idloyaltycard', null],
        'idpanier' => [parent::class, 'idpanier', null],
        'name' => [parent::class, 'name', null],
        'paniers' => [parent::class, 'paniers', null],
        'password' => [parent::class, 'password', null],
        'roles' => [parent::class, 'roles', null],
    ];

    public function __isInitialized(): bool
    {
        return isset($this->lazyObjectState) && $this->isLazyObjectInitialized();
    }

    public function __serialize(): array
    {
        $properties = (array) $this;
        unset($properties["\0" . self::class . "\0lazyObjectState"]);

        return $properties;
    }
}
