<?php

namespace ContainerExVwaYH;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getPromoService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored..service_locator.DtsKEqY.App\Entity\Promo' shared service.
     *
     * @return \App\Entity\Promo
     */
    public static function do($container, $lazyLoad = true)
    {
        throw new RuntimeException('Cannot autowire service ".service_locator.DtsKEqY": it needs an instance of "App\\Entity\\Promo" but this type has been excluded in "config/services.yaml".');
    }
}
