<?php

namespace ContainerRtaFk1m;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_FH0U8W3Service extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.FH0U8W3' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.FH0U8W3'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'coupon' => ['privates', '.errored..service_locator.FH0U8W3.App\\Entity\\Coupon', NULL, 'Cannot autowire service ".service_locator.FH0U8W3": it needs an instance of "App\\Entity\\Coupon" but this type has been excluded in "config/services.yaml".'],
            'entityManager' => ['services', 'doctrine.orm.default_entity_manager', 'getDoctrine_Orm_DefaultEntityManagerService', false],
        ], [
            'coupon' => 'App\\Entity\\Coupon',
            'entityManager' => '?',
        ]);
    }
}
