<?php

namespace ContainerSMH4ITP;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getPanierUserService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'App\Service\PanierUser' shared autowired service.
     *
     * @return \App\Service\PanierUser
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'src'.\DIRECTORY_SEPARATOR.'Service'.\DIRECTORY_SEPARATOR.'PanierUser.php';
        include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'src'.\DIRECTORY_SEPARATOR.'Service'.\DIRECTORY_SEPARATOR.'PromoRecupDate.php';
        include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'src'.\DIRECTORY_SEPARATOR.'Service'.\DIRECTORY_SEPARATOR.'UpdatePriceApresPromo.php';

        $a = new \App\Service\PromoRecupDate();

        return $container->privates['App\\Service\\PanierUser'] = new \App\Service\PanierUser($a, new \App\Service\UpdatePriceApresPromo($a));
    }
}
