controllers:
  resource:
    path: ../src/Controller/
    namespace: App\Controller
  type: attribute

#COMPTE ADMIN
compteadmin:
  path: /compteadmin
  controller: App\Controller\AdminproductsController::adminPage
#PANIER USER
api_user_panier:
  path: /api/user/panier
  controller: App\Controller\UserController::getUserPanier
panier_index:
  path: /user/panier
  controller: App\Controller\UserController::getUserPanier
#ADD QUANTITY PRODUCTS
admin_products_list:
  path: "/admin/products/list"
  controller: 'App\Controller\AdminproductsController::index'

#Contact for anonymous
app_contact:
  path: "/contact"
  controller: 'App\Controller\AccueilController::indexcontact'

#Contact for Users:

api_loyalty_card:
  path: /api/loyalty-card
  controller: App\Controller\UservueController::getLoyaltyCard
  methods: [GET]

user_profile_view:
  path: /user/profile
  controller: App\Controller\UserController::viewProfile

api_login:
  path: /api/login_check
  controller: App\Security\AuthAuthenticator::onAuthenticationSuccess
