<?php

namespace ContainerBWDqkSc;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getCoupon2Service extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored..service_locator.m2Z5Caj.App\Entity\Coupon' shared service.
     *
     * @return \App\Entity\Coupon
     */
    public static function do($container, $lazyLoad = true)
    {
        throw new RuntimeException('Cannot autowire service ".service_locator.m2Z5Caj": it needs an instance of "App\\Entity\\Coupon" but this type has been excluded in "config/services.yaml".');
    }
}
