<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerJLCQ4og\App_KernelPantherDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerJLCQ4og/App_KernelPantherDebugContainer.php') {
    touch(__DIR__.'/ContainerJLCQ4og.legacy');

    return;
}

if (!\class_exists(App_KernelPantherDebugContainer::class, false)) {
    \class_alias(\ContainerJLCQ4og\App_KernelPantherDebugContainer::class, App_KernelPantherDebugContainer::class, false);
}

return new \ContainerJLCQ4og\App_KernelPantherDebugContainer([
    'container.build_hash' => 'JLCQ4og',
    'container.build_id' => 'b4383504',
    'container.build_time' => 1718572657,
    'container.runtime_mode' => \in_array(\PHP_SAPI, ['cli', 'phpdbg', 'embed'], true) ? 'web=0' : 'web=1',
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerJLCQ4og');
