<?php

namespace ContainerCKJRWWn;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getKarserRecaptcha3_Google_RequestMethod_CurlService extends App_KernelTestDebugContainer
{
    /**
     * Gets the private 'karser_recaptcha3.google.request_method.curl' shared service.
     *
     * @return \ReCaptcha\RequestMethod\Curl
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'vendor'.\DIRECTORY_SEPARATOR.'google'.\DIRECTORY_SEPARATOR.'recaptcha'.\DIRECTORY_SEPARATOR.'src'.\DIRECTORY_SEPARATOR.'ReCaptcha'.\DIRECTORY_SEPARATOR.'RequestMethod'.\DIRECTORY_SEPARATOR.'Curl.php';

        return $container->privates['karser_recaptcha3.google.request_method.curl'] = new \ReCaptcha\RequestMethod\Curl();
    }
}
