<?php

namespace ContainerNYC9Uaq;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getKarserRecaptcha3_Google_RecaptchaService extends App_KernelTestDebugContainer
{
    /**
     * Gets the private 'karser_recaptcha3.google.recaptcha' shared service.
     *
     * @return \ReCaptcha\ReCaptcha
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'vendor'.\DIRECTORY_SEPARATOR.'google'.\DIRECTORY_SEPARATOR.'recaptcha'.\DIRECTORY_SEPARATOR.'src'.\DIRECTORY_SEPARATOR.'ReCaptcha'.\DIRECTORY_SEPARATOR.'ReCaptcha.php';

        $container->privates['karser_recaptcha3.google.recaptcha'] = $instance = new \ReCaptcha\ReCaptcha($container->getEnv('RECAPTCHA3_SECRET'), ($container->privates['karser_recaptcha3.google.request_method.curl_post'] ?? $container->load('getKarserRecaptcha3_Google_RequestMethod_CurlPostService')));

        $instance->setScoreThreshold(0.5);

        return $instance;
    }
}
