<?php

namespace ContainerNYC9Uaq;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getKarserRecaptcha3_IpResolverService extends App_KernelTestDebugContainer
{
    /**
     * Gets the private 'karser_recaptcha3.ip_resolver' shared service.
     *
     * @return \Karser\Recaptcha3Bundle\Services\IpResolver
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'vendor'.\DIRECTORY_SEPARATOR.'karser'.\DIRECTORY_SEPARATOR.'karser-recaptcha3-bundle'.\DIRECTORY_SEPARATOR.'Services'.\DIRECTORY_SEPARATOR.'IpResolverInterface.php';
        include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'vendor'.\DIRECTORY_SEPARATOR.'karser'.\DIRECTORY_SEPARATOR.'karser-recaptcha3-bundle'.\DIRECTORY_SEPARATOR.'Services'.\DIRECTORY_SEPARATOR.'IpResolver.php';

        return $container->privates['karser_recaptcha3.ip_resolver'] = new \Karser\Recaptcha3Bundle\Services\IpResolver(($container->services['request_stack'] ??= new \Symfony\Component\HttpFoundation\RequestStack()));
    }
}
