<?php

namespace ContainerNYC9Uaq;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getPromo2Service extends App_KernelTestDebugContainer
{
    /**
     * Gets the private '.errored..service_locator.mcb6ZOo.App\Entity\Promo' shared service.
     *
     * @return \App\Entity\Promo
     */
    public static function do($container, $lazyLoad = true)
    {
        throw new RuntimeException('Cannot autowire service ".service_locator.mcb6ZOo": it needs an instance of "App\\Entity\\Promo" but this type has been excluded in "config/services.yaml".');
    }
}
