<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerJ0mpWzW\App_KernelTestDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerJ0mpWzW/App_KernelTestDebugContainer.php') {
    touch(__DIR__.'/ContainerJ0mpWzW.legacy');

    return;
}

if (!\class_exists(App_KernelTestDebugContainer::class, false)) {
    \class_alias(\ContainerJ0mpWzW\App_KernelTestDebugContainer::class, App_KernelTestDebugContainer::class, false);
}

return new \ContainerJ0mpWzW\App_KernelTestDebugContainer([
    'container.build_hash' => 'J0mpWzW',
    'container.build_id' => '12d67314',
    'container.build_time' => 1718572660,
    'container.runtime_mode' => \in_array(\PHP_SAPI, ['cli', 'phpdbg', 'embed'], true) ? 'web=0' : 'web=1',
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerJ0mpWzW');
