<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerCKJRWWn\App_KernelTestDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerCKJRWWn/App_KernelTestDebugContainer.php') {
    touch(__DIR__.'/ContainerCKJRWWn.legacy');

    return;
}

if (!\class_exists(App_KernelTestDebugContainer::class, false)) {
    \class_alias(\ContainerCKJRWWn\App_KernelTestDebugContainer::class, App_KernelTestDebugContainer::class, false);
}

return new \ContainerCKJRWWn\App_KernelTestDebugContainer([
    'container.build_hash' => 'CKJRWWn',
    'container.build_id' => '15137232',
    'container.build_time' => 1716803899,
    'container.runtime_mode' => \in_array(\PHP_SAPI, ['cli', 'phpdbg', 'embed'], true) ? 'web=0' : 'web=1',
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerCKJRWWn');
