<?php

namespace ContainerBdJFHl1;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_GlqAerrService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.GlqAerr' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.GlqAerr'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'entityManager' => ['services', 'doctrine.orm.default_entity_manager', 'getDoctrine_Orm_DefaultEntityManagerService', false],
            'loyaltyCard' => ['privates', 'App\\Entity\\LoyaltyCard', 'getLoyaltyCardService', true],
            'panierRepository' => ['privates', 'App\\Repository\\PanierRepository', 'getPanierRepositoryService', true],
        ], [
            'entityManager' => '?',
            'loyaltyCard' => 'App\\Entity\\LoyaltyCard',
            'panierRepository' => 'App\\Repository\\PanierRepository',
        ]);
    }
}
