<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerHBTxR30\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerHBTxR30/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerHBTxR30.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerHBTxR30\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerHBTxR30\App_KernelDevDebugContainer([
    'container.build_hash' => 'HBTxR30',
    'container.build_id' => '7a762f55',
    'container.build_time' => 1719148475,
    'container.runtime_mode' => \in_array(\PHP_SAPI, ['cli', 'phpdbg', 'embed'], true) ? 'web=0' : 'web=1',
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerHBTxR30');
