<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerXYsiiti\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerXYsiiti/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerXYsiiti.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerXYsiiti\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerXYsiiti\App_KernelDevDebugContainer([
    'container.build_hash' => 'XYsiiti',
    'container.build_id' => '6aa9d3a2',
    'container.build_time' => 1716759789,
    'container.runtime_mode' => \in_array(\PHP_SAPI, ['cli', 'phpdbg', 'embed'], true) ? 'web=0' : 'web=1',
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerXYsiiti');
