<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerBcdlQYC\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerBcdlQYC/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerBcdlQYC.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerBcdlQYC\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerBcdlQYC\App_KernelDevDebugContainer([
    'container.build_hash' => 'BcdlQYC',
    'container.build_id' => '21bf43e2',
    'container.build_time' => 1718055726,
    'container.runtime_mode' => \in_array(\PHP_SAPI, ['cli', 'phpdbg', 'embed'], true) ? 'web=0' : 'web=1',
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerBcdlQYC');
